name: Release Snap

on:
  push:
    branches:
      - main
    paths:
      - snap/**


env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.2
        with:
          channel: latest/stable

      - name: Install dependencies
        run: |
          sudo snap install --classic snapcraft

      - name: Build Snap
        run: snapcraft pack --output rob-cos-grafana-agent.snap

      - name: Upload and Publish Snap
        run: snapcraft upload --release edge rob-cos-grafana-agent.snap

