#!/bin/sh -e

CONFIGURATION_FILE_PATH=$SNAP_COMMON/configuration/grafana-agent.river

if [ ! -f "$CONFIGURATION_FILE_PATH" ]; then
    echo "Configuration file '$CONFIGURATION_FILE_PATH' does not exist."
    exit 1
fi

snapctl start --enable $SNAP_NAME.grafana-agent
